# Generated by Django 6.0.1 on 2026-01-07 14:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('type', models.CharField(choices=[('telegram', 'telegram'), ('discord', 'discord')], max_length=16)),
                ('platform_chat_id', models.BigIntegerField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('chat_link', models.CharField(blank=True, max_length=512, null=True)),
                ('enable_ai_check', models.BooleanField(default=False)),
                ('prompts_threshold', models.FloatField(default=0.35, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('custom_prompt_threshold', models.FloatField(default=0.35, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('cleanup_mentions', models.BooleanField(default=False)),
                ('cleanup_emojis', models.BooleanField(default=False)),
                ('cleanup_links', models.BooleanField(default=False)),
                ('allowed_link_domains', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='CustomPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('prompt_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'custom_prompts',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('prompt_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prompts',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('telegram_user_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('discord_user_id', models.BigIntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='ChatCustomPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chat')),
                ('custom_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customprompt')),
            ],
            options={
                'db_table': 'chat_custom_prompts',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='custom_prompts',
            field=models.ManyToManyField(blank=True, related_name='chats', through='core.ChatCustomPrompt', to='core.customprompt'),
        ),
        migrations.CreateModel(
            name='ChatPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chat')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prompt')),
            ],
            options={
                'db_table': 'chat_prompts',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='prompts',
            field=models.ManyToManyField(blank=True, related_name='chats', through='core.ChatPrompt', to='core.prompt'),
        ),
        migrations.AddField(
            model_name='customprompt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_prompts', to='core.user'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='core.user'),
        ),
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('external_user_id', models.BigIntegerField()),
                ('trusted', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('valid_messages', models.IntegerField(default=0)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_states', to='core.chat')),
            ],
            options={
                'db_table': 'user_states',
            },
        ),
        migrations.AddConstraint(
            model_name='chatcustomprompt',
            constraint=models.UniqueConstraint(fields=('chat', 'custom_prompt'), name='uk_chat_custom_prompts_chat_id_custom_prompt_id'),
        ),
        migrations.AddConstraint(
            model_name='chatprompt',
            constraint=models.UniqueConstraint(fields=('chat', 'prompt'), name='uk_chat_prompts_chat_id_prompt_id'),
        ),
        migrations.AddConstraint(
            model_name='chat',
            constraint=models.UniqueConstraint(fields=('type', 'platform_chat_id'), name='uk_chats_type_platform_chat_id'),
        ),
        migrations.AddIndex(
            model_name='userstate',
            index=models.Index(fields=['chat', 'external_user_id'], name='idx_user_states_chat_extuser'),
        ),
    ]
