# Generated by Django 6.0.1 on 2026-01-09 07:50

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeStatistics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('messages_checked', models.IntegerField(default=0)),
                ('ai_requests_made', models.IntegerField(default=0)),
                ('messages_deleted', models.IntegerField(default=0)),
                ('name', models.CharField(default='default_stats', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'runtime_statistics',
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='messages_deleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='processed_messages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chat',
            name='spam_detected',
            field=models.IntegerField(default=0),
        ),
    ]
