# Generated by Django 6.0.1 on 2026-01-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alert_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='allowed_mentions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chat',
            name='cleanup_emails',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='max_emoji_count',
            field=models.IntegerField(default=5),
        ),
    ]
