# Generated by Django 6.0.1 on 2026-01-24 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chat_allowed_mentions_chat_clean_up_emails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='custom_prompt_threshold',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='prompts_threshold',
        ),
        migrations.AddField(
            model_name='chat',
            name='min_messages_required',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='chat',
            name='min_observation_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='chatcustomprompt',
            name='threshold',
            field=models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='chatprompt',
            name='threshold',
            field=models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
