//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "chats"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel)]
pub struct Model {
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub is_active: bool,
    pub r#type: String,
    pub platform_chat_id: i64,
    pub title: Option<String>,
    pub chat_link: Option<String>,
    pub enable_ai_check: bool,
    pub prompts_threshold: f64,
    pub custom_prompt_threshold: f64,
    pub cleanup_mentions: bool,
    pub cleanup_emojis: bool,
    pub cleanup_links: bool,
    pub allowed_link_domains: Option<Json>,
    pub user_id: Uuid,
    pub messages_deleted: i32,
    pub processed_messages: i32,
    pub spam_detected: i32,
    pub allowed_mentions: Option<Json>,
    pub cleanup_emails: bool,
    pub max_emoji_count: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    CreatedAt,
    UpdatedAt,
    IsActive,
    Type,
    PlatformChatId,
    Title,
    ChatLink,
    EnableAiCheck,
    PromptsThreshold,
    CustomPromptThreshold,
    CleanupMentions,
    CleanupEmojis,
    CleanupLinks,
    AllowedLinkDomains,
    UserId,
    MessagesDeleted,
    ProcessedMessages,
    SpamDetected,
    AllowedMentions,
    CleanupEmails,
    MaxEmojiCount,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    ChatCustomPrompts,
    ChatPrompts,
    UserStates,
    Users,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::IsActive => ColumnType::Boolean.def(),
            Self::Type => ColumnType::String(StringLen::N(16u32)).def(),
            Self::PlatformChatId => ColumnType::BigInteger.def(),
            Self::Title => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::ChatLink => ColumnType::String(StringLen::N(512u32)).def().null(),
            Self::EnableAiCheck => ColumnType::Boolean.def(),
            Self::PromptsThreshold => ColumnType::Double.def(),
            Self::CustomPromptThreshold => ColumnType::Double.def(),
            Self::CleanupMentions => ColumnType::Boolean.def(),
            Self::CleanupEmojis => ColumnType::Boolean.def(),
            Self::CleanupLinks => ColumnType::Boolean.def(),
            Self::AllowedLinkDomains => ColumnType::JsonBinary.def().null(),
            Self::UserId => ColumnType::Uuid.def(),
            Self::MessagesDeleted => ColumnType::Integer.def(),
            Self::ProcessedMessages => ColumnType::Integer.def(),
            Self::SpamDetected => ColumnType::Integer.def(),
            Self::AllowedMentions => ColumnType::JsonBinary.def().null(),
            Self::CleanupEmails => ColumnType::Boolean.def(),
            Self::MaxEmojiCount => ColumnType::Integer.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::ChatCustomPrompts => Entity::has_many(super::chat_custom_prompts::Entity).into(),
            Self::ChatPrompts => Entity::has_many(super::chat_prompts::Entity).into(),
            Self::UserStates => Entity::has_many(super::user_states::Entity).into(),
            Self::Users => Entity::belongs_to(super::users::Entity)
                .from(Column::UserId)
                .to(super::users::Column::Id)
                .into(),
        }
    }
}

impl Related<super::chat_custom_prompts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatCustomPrompts.def()
    }
}

impl Related<super::chat_prompts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ChatPrompts.def()
    }
}

impl Related<super::user_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserStates.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
