//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::chat_custom_prompts::Entity as ChatCustomPrompts;
pub use super::chat_prompts::Entity as ChatPrompts;
pub use super::chats::Entity as Chats;
pub use super::custom_prompts::Entity as CustomPrompts;
pub use super::prompts::Entity as Prompts;
pub use super::runtime_statistics::Entity as RuntimeStatistics;
pub use super::user_states::Entity as UserStates;
pub use super::users::Entity as Users;
