//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "users"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub id: Uuid,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub is_active: bool,
    pub username: Option<String>,
    pub email: Option<String>,
    pub password_hash: Option<String>,
    pub telegram_user_id: Option<i64>,
    pub discord_user_id: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Id,
    CreatedAt,
    UpdatedAt,
    IsActive,
    Username,
    Email,
    PasswordHash,
    TelegramUserId,
    DiscordUserId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Id,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = Uuid;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
    Chats,
    CustomPrompts,
}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Id => ColumnType::Uuid.def(),
            Self::CreatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::UpdatedAt => ColumnType::TimestampWithTimeZone.def(),
            Self::IsActive => ColumnType::Boolean.def(),
            Self::Username => ColumnType::String(StringLen::N(50u32)).def().null(),
            Self::Email => ColumnType::String(StringLen::N(100u32)).def().null(),
            Self::PasswordHash => ColumnType::String(StringLen::N(255u32)).def().null(),
            Self::TelegramUserId => ColumnType::BigInteger.def().null().unique(),
            Self::DiscordUserId => ColumnType::BigInteger.def().null().unique(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        match self {
            Self::Chats => Entity::has_many(super::chats::Entity).into(),
            Self::CustomPrompts => Entity::has_many(super::custom_prompts::Entity).into(),
        }
    }
}

impl Related<super::chats::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Chats.def()
    }
}

impl Related<super::custom_prompts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CustomPrompts.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
